security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
#                default_target_path: pluvio # La page où l'on veut rediriger après connexion
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/api, roles: PUBLIC_ACCESS }  # <-- ✅ rendre l’API accessible sans login
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }


    role_hierarchy:
        ROLE_EDITOR: ROLE_USER
        ROLE_ADMIN: ROLE_EDITOR
